services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  db:
    image: mysql:8.0.30-debian
    env_file: .env
    ports:
      - 3306:3306
    # volumes:
    #   - ./.docker/dbdata:/var/lib/mysql
